Minor bugfix for relative link selector
The relative link selector causes the following error message in JQuery  1.9.1 and JQuery 1.7.2:
Error: Syntax error, unrecognized expression: [href=^"/"]

I reversed the carat('^') and equals('=') to refer to the first character of the href attribute.